name: Update README

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count commits
        id: count_commits
        run: echo "commits_count=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/{commits_count}/$commits_count/g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update README with commit count" || echo "No changes to commit"

    - name: Push changes
  run: git push https://x-access-token:${{ secrets.PAT }}@github.com/Nati-darse/Nati-darse.git
